---
- name: SAP Migration | System copy import on GCP
  hosts: gcp_sap
  become: true
  vars_files:
    - ../inventory/group_vars/all.yml
    - ../inventory/group_vars/sap_ha_cluster.yml
    - ../inventory/group_vars/profiles/{{ sap_database_type }}_ha.yml
  roles:
    - acme.sap_migration.system_copy_import
